service: backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  profile: cn

# you can overwrite defaults here
  stage: dev
  region: cn-north-1

custom:
  appSync:
    name: sls-deployment
    authenticationType: API_KEY
    apiKeys:
      - name: test # name of the api key
        description: 'test api key'
        expiresAfter: 30d # api key life time
    schema: schema.graphql
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: Users
        type: Query
        field: getTodo
        request: "Query.getTodo.req.vtl"
        response: "Query.getTodo.res.vtl"
      - dataSource: Users
        type: Query
        field: listTodos
        request: "Query.listTodos.req.vtl"
        response: "Query.listTodos.res.vtl"
      - dataSource: Users
        type: Query
        field: syncTodos
        request: "Query.syncTodos.req.vtl"
        response: "Query.syncTodos.res.vtl"
      - dataSource: Users
        type: Mutation
        field: createTodo
        request: "Mutation.createTodo.req.vtl"
        response: "Mutation.createTodo.res.vtl"
        sync:
          conflictDetection: VERSION
          conflictHandler: AUTOMERGE
      - dataSource: Users
        type: Mutation
        field: deleteTodo
        request: "Mutation.deleteTodo.req.vtl"
        response: "Mutation.deleteTodo.res.vtl"
        sync:
          conflictDetection: VERSION
          conflictHandler: AUTOMERGE
      - dataSource: Users
        type: Mutation
        field: updateTodo
        request: "Mutation.updateTodo.req.vtl"
        response: "Mutation.updateTodo.res.vtl"
        sync:
          conflictDetection: VERSION
          conflictHandler: AUTOMERGE
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: { Ref: UserTable }
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
          versioned: true
          deltaSyncConfig:
            baseTableTTL: 0 # (default, not required) # The amount of time (in minutes) items should be kept in the base table when deleted. Set to 0 to delete items in the base table immediately
            deltaSyncTableName: { Ref: MyTableDelta } # required # The Delta Sync table name
            deltaSyncTableTTL: 60

resources:
  Resources:
    AppSyncDynamoDBServiceRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Description: The role to handle dynamodb
        ManagedPolicyArns: 
          - arn:aws-cn:iam::aws:policy/AmazonDynamoDBFullAccess
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: "TestTableAppsyncDeployment"
        AttributeDefinitions: 
          - 
            AttributeName: "name"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "name"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
    MyTableDelta:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: "AppsyncDeltaDeployment"
        AttributeDefinitions: 
          - 
            AttributeName: "ds_pk"
            AttributeType: "S"
          - 
            AttributeName: "ds_sk"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "ds_pk"
            KeyType: "HASH"
          - 
            AttributeName: "ds_sk"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TimeToLiveSpecification: 
            AttributeName: _ttl
            Enabled: true


plugins:
  - serverless-appsync-plugin
